FROM node:7.9.0

WORKDIR /acton-tracker

# COPY . /acton-tracker
# RUN npm cache clean \
#  && npm install \
#  && npm rebuild node-sass
# CMD ["npm", "start"]

ENV NODE_CONFIG_DIR ./nconfig
ENV DB_HOST acton_mysql
